export interface IndustryService {
  name:  string
  price: string
  desc:  string
}

export interface IndustryData {
  slug:        string
  name:        string
  emoji:       string
  heroImage:   string
  tagline:     string
  description: string
  gradient:    string   // Tailwind gradient for hero overlay / CTA
  lightBg:     string   // Tailwind bg class for strips (light)
  accentText:  string   // Tailwind text color
  accentBg:    string   // Tailwind bg for buttons
  accentHover: string
  price:       string
  delivery:    string
  badge:       string | null
  modalFeatures: { icon: string; text: string }[]
  services:    IndustryService[]
  features:    { emoji: string; title: string; desc: string }[]
  demoName:    string   // fake business name shown in demo
  demoSub:     string   // fake tagline shown in demo
}

export const newIndustries: IndustryData[] = [
  // ─── FOOD ───────────────────────────────────────────────
  {
    slug:        'dhaba',
    name:        'Dhaba / Cloud Kitchen',
    emoji:       '🥘',
    heroImage:   'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=1200&q=80',
    tagline:     'Online ordering & delivery system',
    description: 'A modern website for your dhaba or cloud kitchen with online ordering, Zomato-style tracking, and Razorpay payments — all without paying Zomato commission.',
    gradient:    'from-red-500 to-orange-500',
    lightBg:     'bg-orange-50',
    accentText:  'text-orange-600',
    accentBg:    'bg-orange-500',
    accentHover: 'hover:bg-orange-600',
    price:       '₹9,999', delivery: '7 days', badge: null,
    demoName: 'Maa Ka Dhaba', demoSub: 'Pure Home Cooked Food · Delhi',
    modalFeatures: [
      { icon: '📱', text: 'Online ordering — customers order from your website directly' },
      { icon: '🚴', text: 'Delivery zone map — show areas you deliver to' },
      { icon: '💳', text: 'Razorpay payments — UPI, cards, wallets' },
      { icon: '📋', text: 'Digital menu with daily specials & photos' },
      { icon: '🔔', text: 'Order notification on WhatsApp the moment someone orders' },
      { icon: '📊', text: 'Daily order & revenue dashboard' },
    ],
    features: [
      { emoji: '📱', title: 'Order Online',       desc: 'Customers order directly from your website — no app needed, no commission.' },
      { emoji: '🚴', title: 'Delivery Zones',     desc: 'Show your delivery area on a map. Set minimum order and delivery charges.' },
      { emoji: '📋', title: 'Digital Menu',       desc: 'Add / remove items, update prices, mark "Sold Out" — from your phone.' },
      { emoji: '🔔', title: 'Instant Alerts',     desc: 'WhatsApp notification the moment a customer places an order.' },
    ],
    services: [
      { name: 'Lunch Thali',     price: '₹149', desc: 'Dal, sabzi, roti, rice, salad — full meal' },
      { name: 'Dinner Special',  price: '₹199', desc: 'Paneer + 2 sabzi + naan + dessert' },
      { name: 'Family Pack',     price: '₹499', desc: 'For 4 people · Full spread with sweet' },
    ],
  },
  {
    slug:        'bakery',
    name:        'Bakery & Cafe',
    emoji:       '☕',
    heroImage:   'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=1200&q=80',
    tagline:     'Pre-orders, custom cakes & cafe menu',
    description: 'A beautiful bakery website for pre-ordering cakes, custom orders for birthdays and weddings, and showcasing your cafe menu to attract walk-ins.',
    gradient:    'from-amber-500 to-yellow-500',
    lightBg:     'bg-amber-50',
    accentText:  'text-amber-700',
    accentBg:    'bg-amber-500',
    accentHover: 'hover:bg-amber-600',
    price:       '₹9,999', delivery: '7 days', badge: null,
    demoName: 'The Flour & Brew', demoSub: 'Artisan Bakery & Specialty Coffee · Pune',
    modalFeatures: [
      { icon: '🎂', text: 'Custom cake orders — size, flavour, message, delivery date' },
      { icon: '📅', text: 'Pre-order system — order 24 hrs in advance, no walk-in rush' },
      { icon: '☕', text: 'Cafe menu with photos and prices' },
      { icon: '📸', text: 'Gallery showcase — your best creations' },
      { icon: '💳', text: 'Advance payment with Razorpay' },
      { icon: '⭐', text: 'Google reviews + Instagram feed integration' },
    ],
    features: [
      { emoji: '🎂', title: 'Custom Cake Orders', desc: 'Customers fill a form — flavour, size, message, date. You confirm on WhatsApp.' },
      { emoji: '📅', title: 'Pre-order System',   desc: 'Accept orders 24–48 hrs in advance. Manage your kitchen better.' },
      { emoji: '📸', title: 'Photo Gallery',      desc: 'Show off your best cakes, pastries, and bread. Converts visitors instantly.' },
      { emoji: '💳', title: 'Advance Payments',   desc: 'Collect 50% advance with Razorpay. No more last-minute cancellations.' },
    ],
    services: [
      { name: 'Custom Birthday Cake', price: '₹799+', desc: '1 kg · choose flavour & design' },
      { name: 'Wedding Cake',         price: '₹3,500+', desc: 'Multi-tier · consultation included' },
      { name: 'Cafe Cappuccino',      price: '₹180', desc: 'Double shot · oat milk available' },
    ],
  },
  {
    slug:        'catering',
    name:        'Catering Service',
    emoji:       '🍱',
    heroImage:   'https://images.unsplash.com/photo-1555244162-803834f70033?w=1200&q=80',
    tagline:     'Event catering bookings & menu packages',
    description: 'A professional catering website with menu packages, per-plate pricing, event enquiry forms, and a gallery of past events to build trust.',
    gradient:    'from-orange-500 to-red-500',
    lightBg:     'bg-orange-50',
    accentText:  'text-orange-600',
    accentBg:    'bg-orange-500',
    accentHover: 'hover:bg-orange-600',
    price:       '₹9,999', delivery: '7 days', badge: null,
    demoName: 'Royal Caterers', demoSub: 'Premium Event Catering · Jaipur',
    modalFeatures: [
      { icon: '🍽️', text: 'Menu packages — veg/non-veg, per-plate pricing, custom menus' },
      { icon: '📝', text: 'Event enquiry form — date, guests, event type, location' },
      { icon: '📸', text: 'Past events gallery — weddings, corporate, birthdays' },
      { icon: '💬', text: 'WhatsApp quick quote button' },
      { icon: '⭐', text: 'Client testimonials and reviews' },
      { icon: '📞', text: 'Callback request for large events' },
    ],
    features: [
      { emoji: '🍽️', title: 'Menu Packages',   desc: 'Display veg/non-veg packages with per-plate pricing clearly.' },
      { emoji: '📝', title: 'Event Enquiry',    desc: 'Structured form captures all details — date, guests, type, location.' },
      { emoji: '📸', title: 'Events Gallery',   desc: 'Showcase weddings, birthdays, corporate events. Trust = bookings.' },
      { emoji: '💬', title: 'WhatsApp Quote',   desc: 'One-tap WhatsApp button to get instant quote request.' },
    ],
    services: [
      { name: 'Wedding Package', price: '₹350/plate', desc: '10+ dishes · live counter · service staff' },
      { name: 'Corporate Lunch', price: '₹180/plate', desc: '5 dishes · tea/coffee · setup included' },
      { name: 'Birthday Party',  price: '₹250/plate', desc: '8 dishes · cake cutting · decoration' },
    ],
  },
  // ─── HEALTH ─────────────────────────────────────────────
  {
    slug:        'dental',
    name:        'Dental Clinic',
    emoji:       '🦷',
    heroImage:   'https://images.unsplash.com/photo-1606811971618-4486d14f3f99?w=1200&q=80',
    tagline:     'Appointments, treatments & patient trust',
    description: 'A professional dental clinic website that shows your services, builds patient trust with before/after photos, and lets patients book appointments online.',
    gradient:    'from-sky-500 to-blue-600',
    lightBg:     'bg-sky-50',
    accentText:  'text-sky-600',
    accentBg:    'bg-sky-500',
    accentHover: 'hover:bg-sky-600',
    price:       '₹9,999', delivery: '7 days', badge: null,
    demoName: 'Bright Smile Dental', demoSub: 'Advanced Dental Care · Bengaluru',
    modalFeatures: [
      { icon: '📅', text: 'Online appointment booking with dentist selection' },
      { icon: '🦷', text: 'Services page — cleaning, braces, implants, whitening' },
      { icon: '📸', text: 'Before & after gallery to build trust' },
      { icon: '👨‍⚕️', text: 'Doctor profiles with qualifications & experience' },
      { icon: '📱', text: 'WhatsApp confirmation + reminder' },
      { icon: '⭐', text: 'Google reviews showcase' },
    ],
    features: [
      { emoji: '📅', title: 'Online Booking',   desc: 'Patients book time slots without calling. View by doctor or treatment type.' },
      { emoji: '📸', title: 'Before & After',   desc: 'A photo gallery showing real patient results is your best marketing tool.' },
      { emoji: '👨‍⚕️', title: 'Doctor Profiles', desc: 'Show qualifications, specialisations, and years of experience.' },
      { emoji: '📱', title: 'Auto Reminders',   desc: 'WhatsApp reminder before the appointment reduces no-shows by 60%.' },
    ],
    services: [
      { name: 'Teeth Cleaning',   price: '₹800',   desc: 'Scaling & polishing · 30 min' },
      { name: 'Dental Braces',    price: '₹18,000+', desc: 'Metal / ceramic · consultation included' },
      { name: 'Teeth Whitening',  price: '₹3,500',  desc: 'Professional whitening · 1 session' },
    ],
  },
  {
    slug:        'pharmacy',
    name:        'Pharmacy',
    emoji:       '💊',
    heroImage:   'https://images.unsplash.com/photo-1631549916768-4119b2e5f926?w=1200&q=80',
    tagline:     'Online medicine ordering & prescription upload',
    description: 'A pharmacy website where customers can upload prescriptions, browse OTC products, and request home delivery — fully integrated with WhatsApp.',
    gradient:    'from-green-500 to-teal-600',
    lightBg:     'bg-green-50',
    accentText:  'text-green-700',
    accentBg:    'bg-green-600',
    accentHover: 'hover:bg-green-700',
    price:       '₹9,999', delivery: '7 days', badge: null,
    demoName: 'MedCare Pharmacy', demoSub: 'Your Trusted Medical Store · Mumbai',
    modalFeatures: [
      { icon: '📋', text: 'Prescription upload — customer clicks photo, uploads, you confirm' },
      { icon: '🚚', text: 'Home delivery request with address and time slot' },
      { icon: '💊', text: 'OTC product catalog with prices' },
      { icon: '📱', text: 'WhatsApp order confirmation & delivery updates' },
      { icon: '🔔', text: 'Medicine reminder signup — recurring customers' },
      { icon: '⏰', text: 'Operating hours & emergency contact visible prominently' },
    ],
    features: [
      { emoji: '📋', title: 'Prescription Upload', desc: 'Customer uploads photo of prescription. You confirm via WhatsApp in minutes.' },
      { emoji: '🚚', title: 'Home Delivery',       desc: 'Delivery request form with address, preferred time, and contact.' },
      { emoji: '💊', title: 'Product Catalog',     desc: 'OTC medicines, vitamins, healthcare products with prices.' },
      { emoji: '📱', title: 'WhatsApp Updates',    desc: 'Order confirmation and delivery updates sent on WhatsApp.' },
    ],
    services: [
      { name: 'Prescription Medicines', price: 'As prescribed', desc: 'Upload Rx · home delivery in 2 hrs' },
      { name: 'OTC Products',           price: 'MRP price', desc: 'Vitamins, first aid, personal care' },
      { name: 'Health Checkup Strips',  price: '₹299+', desc: 'Blood glucose, BP monitors, etc.' },
    ],
  },
  {
    slug:        'gym',
    name:        'Gym & Fitness Center',
    emoji:       '💪',
    heroImage:   'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=1200&q=80',
    tagline:     'Memberships, classes & trainer profiles',
    description: 'A high-energy gym website with membership plans, class schedules, trainer profiles, and a free trial booking form that converts visitors into members.',
    gradient:    'from-red-600 to-rose-500',
    lightBg:     'bg-red-50',
    accentText:  'text-red-600',
    accentBg:    'bg-red-600',
    accentHover: 'hover:bg-red-700',
    price:       '₹9,999', delivery: '7 days', badge: null,
    demoName: 'IronEdge Fitness', demoSub: 'Transform Your Body · Hyderabad',
    modalFeatures: [
      { icon: '🏋️', text: 'Membership plans — monthly, quarterly, yearly with pricing' },
      { icon: '📅', text: 'Class schedule — Zumba, CrossFit, Yoga, Cardio timings' },
      { icon: '👨‍💼', text: 'Trainer profiles with certifications & specialisations' },
      { icon: '🎯', text: 'Free trial booking form to capture leads' },
      { icon: '📸', text: 'Transformation gallery — member before/after photos' },
      { icon: '📱', text: 'WhatsApp enquiry for membership queries' },
    ],
    features: [
      { emoji: '🏋️', title: 'Membership Plans',  desc: 'Clear monthly/quarterly/yearly pricing. Members buy online with Razorpay.' },
      { emoji: '📅', title: 'Class Schedule',     desc: "Live timetable — Zumba, CrossFit, Yoga. Customers see what's on today." },
      { emoji: '👨‍💼', title: 'Trainer Profiles',  desc: 'Show certifications, specialisations, and member testimonials per trainer.' },
      { emoji: '🎯', title: 'Free Trial Form',    desc: '1 free trial converts to paid membership. Capture their details online.' },
    ],
    services: [
      { name: 'Monthly Membership', price: '₹1,200', desc: 'Full gym access · all equipment' },
      { name: 'Personal Training',  price: '₹500/session', desc: '1-on-1 with certified trainer' },
      { name: 'Group Classes',      price: '₹300/class', desc: 'Zumba / Yoga / CrossFit' },
    ],
  },
  // ─── STAY ───────────────────────────────────────────────
  {
    slug:        'pg-hostel',
    name:        'PG & Hostel',
    emoji:       '🏠',
    heroImage:   'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=1200&q=80',
    tagline:     'Room listings, pricing & vacancy status',
    description: 'A simple, clear PG/hostel website showing room types, pricing, amenities, and live vacancy status — so students and working professionals find you before anyone else.',
    gradient:    'from-violet-500 to-purple-600',
    lightBg:     'bg-violet-50',
    accentText:  'text-violet-700',
    accentBg:    'bg-violet-600',
    accentHover: 'hover:bg-violet-700',
    price:       '₹9,999', delivery: '7 days', badge: null,
    demoName: 'HomeAway PG', demoSub: 'Comfortable PG for Students & Professionals · Bengaluru',
    modalFeatures: [
      { icon: '🛏️', text: 'Room listings — single, double, triple occupancy with photos' },
      { icon: '🟢', text: 'Live vacancy status — "2 rooms available" badge' },
      { icon: '📋', text: 'Amenities list — WiFi, AC, meals, laundry, security' },
      { icon: '📝', text: 'Enquiry/booking form with move-in date' },
      { icon: '📸', text: 'Photo gallery — rooms, common areas, kitchen' },
      { icon: '🗺️', text: 'Location map with nearby colleges, metro, landmarks' },
    ],
    features: [
      { emoji: '🛏️', title: 'Room Listings',    desc: 'Separate pages for single/double/triple with photos and pricing.' },
      { emoji: '🟢', title: 'Vacancy Status',   desc: 'Live "X rooms available" badge — creates urgency and saves your time.' },
      { emoji: '📋', title: 'Amenities Page',   desc: 'Show WiFi, meals, security, laundry clearly. Sells the stay before a call.' },
      { emoji: '🗺️', title: 'Location Map',    desc: 'Show proximity to colleges, offices, metro station.' },
    ],
    services: [
      { name: 'Single Occupancy', price: '₹8,000/mo', desc: 'AC room · attached bath · meals included' },
      { name: 'Double Sharing',   price: '₹5,500/mo', desc: 'AC room · common bath · meals included' },
      { name: 'Triple Sharing',   price: '₹4,000/mo', desc: 'Non-AC · common bath · meals extra' },
    ],
  },
  // ─── TRAVEL ─────────────────────────────────────────────
  {
    slug:        'travel-agency',
    name:        'Travel Agency',
    emoji:       '✈️',
    heroImage:   'https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=1200&q=80',
    tagline:     'Tour packages, bookings & holiday planning',
    description: 'A stunning travel agency website showcasing tour packages with itineraries, pricing, photos, and instant WhatsApp enquiry — designed to inspire and convert.',
    gradient:    'from-sky-500 to-blue-600',
    lightBg:     'bg-sky-50',
    accentText:  'text-sky-600',
    accentBg:    'bg-sky-500',
    accentHover: 'hover:bg-sky-600',
    price:       '₹9,999', delivery: '7 days', badge: '⭐ Popular',
    demoName: 'Wanderlust Holidays', demoSub: 'Curated Travel Experiences · India & Abroad',
    modalFeatures: [
      { icon: '🗺️', text: 'Tour packages with day-wise itinerary, inclusions & exclusions' },
      { icon: '📸', text: 'Destination gallery — beautiful photos that inspire travel' },
      { icon: '💬', text: 'WhatsApp enquiry button on every package' },
      { icon: '💳', text: 'Advance booking with Razorpay payment' },
      { icon: '⭐', text: 'Traveller reviews & trip photos' },
      { icon: '📞', text: 'Custom tour enquiry form for group bookings' },
    ],
    features: [
      { emoji: '🗺️', title: 'Tour Packages',   desc: 'Each package shows day-wise itinerary, what\'s included, pricing, and gallery.' },
      { emoji: '📸', title: 'Destination Pages', desc: 'Beautiful destination photography drives enquiries more than any ad.' },
      { emoji: '💬', title: 'WhatsApp Enquiry', desc: 'One tap WhatsApp button on every package page.' },
      { emoji: '💳', title: 'Online Booking',   desc: 'Accept advance booking amount via Razorpay to confirm the tour.' },
    ],
    services: [
      { name: 'Rajasthan Royals (7N/8D)', price: '₹18,500/person', desc: 'Jaipur · Jodhpur · Jaisalmer · Udaipur' },
      { name: 'Kerala Backwaters (5N/6D)', price: '₹14,000/person', desc: 'Munnar · Alleppey · Kovalam' },
      { name: 'Manali Adventure (4N/5D)', price: '₹12,000/person', desc: 'Solang · Rohtang · Kasol' },
    ],
  },
  {
    slug:        'cab-service',
    name:        'Cab & Taxi Service',
    emoji:       '🚕',
    heroImage:   'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=1200&q=80',
    tagline:     'Online cab booking & fleet showcase',
    description: 'A clean cab booking website for local taxi services, outstation rides, and airport transfers — with instant WhatsApp booking and live driver tracking.',
    gradient:    'from-yellow-500 to-amber-500',
    lightBg:     'bg-yellow-50',
    accentText:  'text-yellow-700',
    accentBg:    'bg-yellow-500',
    accentHover: 'hover:bg-yellow-600',
    price:       '₹9,999', delivery: '5 days', badge: null,
    demoName: 'SpeedGo Cabs', demoSub: 'Safe · Reliable · Affordable · Pan India',
    modalFeatures: [
      { icon: '🚗', text: 'Cab booking form — pickup, drop, date, time, cab type' },
      { icon: '💬', text: 'WhatsApp booking confirmation in 2 minutes' },
      { icon: '💰', text: 'Transparent pricing — per km rate or fixed route pricing' },
      { icon: '🛻', text: 'Fleet showcase — Sedan, SUV, Tempo Traveller, Buses' },
      { icon: '✈️', text: 'Airport transfer and outstation booking' },
      { icon: '⭐', text: 'Driver ratings and customer testimonials' },
    ],
    features: [
      { emoji: '🚗', title: 'Online Booking',    desc: 'Customers fill pickup/drop, date, time. You confirm on WhatsApp in 2 mins.' },
      { emoji: '💰', title: 'Clear Pricing',     desc: 'Show per-km rates or fixed route prices upfront. No surprises.' },
      { emoji: '🛻', title: 'Fleet Showcase',    desc: 'Show your vehicles with capacity, AC/non-AC, and pricing.' },
      { emoji: '✈️', title: 'Airport Transfers', desc: 'Dedicated airport transfer booking page. High-value, repeat clients.' },
    ],
    services: [
      { name: 'Local (within city)', price: '₹12/km', desc: 'Min 4 hrs · AC Sedan' },
      { name: 'Outstation (one-way)', price: '₹14/km', desc: 'Min 300 km · AC Sedan' },
      { name: 'Airport Transfer',    price: '₹800 flat', desc: 'Up to 30 km · includes waiting' },
    ],
  },
  // ─── EDUCATION ──────────────────────────────────────────
  {
    slug:        'school',
    name:        'School & College',
    emoji:       '🏫',
    heroImage:   'https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=1200&q=80',
    tagline:     'Admissions, academics & parent portal',
    description: 'A professional school website that showcases academic excellence, simplifies admissions, and keeps parents connected with events, notices, and results.',
    gradient:    'from-indigo-600 to-blue-600',
    lightBg:     'bg-indigo-50',
    accentText:  'text-indigo-700',
    accentBg:    'bg-indigo-600',
    accentHover: 'hover:bg-indigo-700',
    price:       '₹12,999', delivery: '10 days', badge: null,
    demoName: 'Sunrise Public School', demoSub: 'Nurturing Future Leaders Since 1998 · Noida',
    modalFeatures: [
      { icon: '📝', text: 'Online admission enquiry form with class and year selection' },
      { icon: '🏆', text: 'Achievements & results showcase — board toppers, competitions' },
      { icon: '📅', text: 'Academic calendar — events, exams, holidays' },
      { icon: '👩‍🏫', text: 'Faculty profiles with qualifications' },
      { icon: '📸', text: 'Photo/video gallery — events, sports day, annual function' },
      { icon: '📞', text: 'Parent notice board — circulars and fee reminders' },
    ],
    features: [
      { emoji: '📝', title: 'Online Admissions', desc: 'Admission enquiry form captures name, class, contact. Auto-response via WhatsApp.' },
      { emoji: '🏆', title: 'Achievements',      desc: 'Board results, sports victories, competition wins build immediate credibility.' },
      { emoji: '📅', title: 'Academic Calendar', desc: 'Exam dates, events, and holidays visible to parents always.' },
      { emoji: '📸', title: 'Events Gallery',    desc: 'Annual function, sports day, science fair — parents love this.' },
    ],
    services: [
      { name: 'Nursery – Class 5',  price: '₹35,000/yr', desc: 'English medium · CBSE affiliated' },
      { name: 'Class 6 – Class 10', price: '₹42,000/yr', desc: 'Science & Commerce streams' },
      { name: 'Class 11 – Class 12', price: '₹48,000/yr', desc: 'PCM / PCB / Commerce' },
    ],
  },
  // ─── EVENTS ─────────────────────────────────────────────
  {
    slug:        'wedding-planner',
    name:        'Wedding Planner',
    emoji:       '💒',
    heroImage:   'https://images.unsplash.com/photo-1519741497674-611481863552?w=1200&q=80',
    tagline:     'Dream weddings, venue coordination & packages',
    description: 'A magical wedding planning website showcasing past celebrations, vendor networks, package pricing, and a consultation booking form for couples planning their big day.',
    gradient:    'from-rose-400 to-pink-600',
    lightBg:     'bg-rose-50',
    accentText:  'text-rose-600',
    accentBg:    'bg-rose-500',
    accentHover: 'hover:bg-rose-600',
    price:       '₹12,999', delivery: '10 days', badge: '🌸 Premium',
    demoName: 'The Wedding Story', demoSub: 'Crafting Unforgettable Celebrations · Pan India',
    modalFeatures: [
      { icon: '💒', text: 'Wedding gallery — real weddings with stories and photos' },
      { icon: '📦', text: 'Packages — basic, premium, luxury with inclusions' },
      { icon: '📝', text: 'Consultation booking form — date, guest count, budget, venue preference' },
      { icon: '🤝', text: 'Vendor network — caterers, photographers, decorators, makeup' },
      { icon: '⭐', text: 'Bride/groom testimonials' },
      { icon: '📅', text: 'Event timeline and planning checklist' },
    ],
    features: [
      { emoji: '💒', title: 'Real Weddings',    desc: 'Photo stories from past weddings create emotional connection and bookings.' },
      { emoji: '📦', title: 'Clear Packages',   desc: 'Basic/premium/luxury tiers with exact inclusions eliminate price confusion.' },
      { emoji: '🤝', title: 'Vendor Network',   desc: 'Your photographer, decorator, caterer network is your biggest value add.' },
      { emoji: '📝', title: 'Enquiry Form',     desc: 'Date, city, guest count, budget, and preferences — all in one form.' },
    ],
    services: [
      { name: 'Basic Package',   price: '₹1.5L', desc: 'Decor + coordination · up to 200 guests' },
      { name: 'Premium Package', price: '₹3.5L', desc: 'Full coordination · vendors · 500 guests' },
      { name: 'Luxury Package',  price: '₹8L+',  desc: 'Destination wedding · all inclusive' },
    ],
  },
  {
    slug:        'event-management',
    name:        'Event Management',
    emoji:       '🎉',
    heroImage:   'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=1200&q=80',
    tagline:     'Corporate events, launches & celebrations',
    description: 'A professional event management website showcasing past events, service capabilities, client logos, and a quick enquiry form for corporate and social event bookings.',
    gradient:    'from-violet-600 to-purple-600',
    lightBg:     'bg-violet-50',
    accentText:  'text-violet-700',
    accentBg:    'bg-violet-600',
    accentHover: 'hover:bg-violet-700',
    price:       '₹9,999', delivery: '7 days', badge: null,
    demoName: 'Grand Events Co.', demoSub: 'Corporate · Social · Experiential Events · Mumbai',
    modalFeatures: [
      { icon: '🎉', text: 'Services — corporate events, product launches, conferences, birthdays' },
      { icon: '📸', text: 'Events gallery with videos and highlights' },
      { icon: '🏢', text: 'Client logos — brand credibility for corporate clients' },
      { icon: '📝', text: 'Event enquiry form — type, date, guests, venue, budget' },
      { icon: '🤝', text: 'Vendor & logistics network showcase' },
      { icon: '⭐', text: 'Client testimonials and case studies' },
    ],
    features: [
      { emoji: '🎉', title: 'Services Grid',    desc: 'Corporate, social, product launch — separate service pages for each.' },
      { emoji: '📸', title: 'Event Gallery',    desc: 'Photo and video highlights from past events. The best sales tool.' },
      { emoji: '🏢', title: 'Client Logos',     desc: 'Corporate client logos build trust with new business clients instantly.' },
      { emoji: '📝', title: 'Quick Enquiry',    desc: 'Date, type, headcount, venue, and budget captured in one form.' },
    ],
    services: [
      { name: 'Corporate Conference', price: '₹50,000+', desc: 'AV · stage · catering · branding' },
      { name: 'Product Launch',       price: '₹35,000+', desc: 'Theme · PR coordination · photography' },
      { name: 'Birthday Celebration', price: '₹15,000+', desc: 'Decor · cake · entertainment · invites' },
    ],
  },
  // ─── RETAIL ─────────────────────────────────────────────
  {
    slug:        'clothing-boutique',
    name:        'Clothing Boutique',
    emoji:       '👗',
    heroImage:   'https://images.unsplash.com/photo-1558769132-cb1aea458c5e?w=1200&q=80',
    tagline:     'Online store for ethnic & fashion wear',
    description: 'A stylish boutique website with product catalog, WhatsApp ordering, Razorpay checkout, and a lookbook gallery — turning followers into paying customers.',
    gradient:    'from-fuchsia-500 to-pink-600',
    lightBg:     'bg-fuchsia-50',
    accentText:  'text-fuchsia-700',
    accentBg:    'bg-fuchsia-600',
    accentHover: 'hover:bg-fuchsia-700',
    price:       '₹9,999', delivery: '7 days', badge: null,
    demoName: 'Aura Boutique', demoSub: 'Premium Ethnic & Designer Wear · Surat',
    modalFeatures: [
      { icon: '👗', text: 'Product catalog with photos, sizes, colors, and pricing' },
      { icon: '💬', text: 'WhatsApp order button on every product' },
      { icon: '💳', text: 'Razorpay checkout for direct online purchase' },
      { icon: '📸', text: 'Lookbook / styled photoshoots gallery' },
      { icon: '🎁', text: 'Custom tailoring order form with measurements' },
      { icon: '🏷️', text: 'Sale / discount section with countdown timer' },
    ],
    features: [
      { emoji: '👗', title: 'Product Catalog',  desc: 'Categories for sarees, kurtis, lehengas, western — with size and color filters.' },
      { emoji: '📸', title: 'Lookbook Gallery', desc: 'Styled photos showing how garments look when worn. Drives purchase decisions.' },
      { emoji: '💬', title: 'WhatsApp Orders',  desc: 'Customers can enquire or order via WhatsApp directly from product page.' },
      { emoji: '💳', title: 'Online Checkout',  desc: 'Direct purchase with Razorpay. UPI, cards, wallets, EMI — all accepted.' },
    ],
    services: [
      { name: 'Ready-to-Wear Kurti',  price: '₹799+',   desc: 'Cotton · silk · georgette · various prints' },
      { name: 'Bridal Lehenga',       price: '₹15,000+', desc: 'Custom · blouse stitching included' },
      { name: 'Custom Tailoring',     price: '₹500+',    desc: 'Blouse · salwar · any garment stitching' },
    ],
  },
  {
    slug:        'jewellery-shop',
    name:        'Jewellery Shop',
    emoji:       '💍',
    heroImage:   'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=1200&q=80',
    tagline:     'Jewellery catalog, custom orders & trust building',
    description: 'An elegant jewellery website showcasing gold, silver, and diamond collections with BIS hallmark badges, custom order forms, and a booking system for try-before-you-buy.',
    gradient:    'from-yellow-600 to-amber-700',
    lightBg:     'bg-yellow-50',
    accentText:  'text-yellow-700',
    accentBg:    'bg-yellow-600',
    accentHover: 'hover:bg-yellow-700',
    price:       '₹9,999', delivery: '7 days', badge: null,
    demoName: 'Sona Jewellers', demoSub: 'Trusted Jewellers Since 1972 · Rajkot',
    modalFeatures: [
      { icon: '💍', text: 'Collection catalog — gold, silver, diamond, kundan, meenakari' },
      { icon: '✅', text: 'BIS Hallmark & certification badges for trust' },
      { icon: '📝', text: 'Custom order form — design, metal, stone, budget' },
      { icon: '📅', text: 'Store visit appointment for high-value purchases' },
      { icon: '📸', text: 'Design gallery and bridal collection lookbook' },
      { icon: '💰', text: 'Today\'s gold rate displayed live' },
    ],
    features: [
      { emoji: '💍', title: 'Collection Catalog', desc: 'Browse by occasion — bridal, daily wear, gifting. Filter by metal and budget.' },
      { emoji: '✅', title: 'Trust Badges',       desc: 'BIS hallmark, certification, and years in business displayed prominently.' },
      { emoji: '💰', title: 'Live Gold Rate',     desc: 'Today\'s gold rate widget builds transparency and drives walk-in traffic.' },
      { emoji: '📅', title: 'Store Appointment',  desc: 'For high-value purchases, a store visit booking system reduces wait time.' },
    ],
    services: [
      { name: 'Gold Jewellery',    price: 'Market rate + making', desc: 'Rings · necklaces · bangles · earrings' },
      { name: 'Diamond Jewellery', price: '₹15,000+',            desc: 'Solitaire · cluster · certified stones' },
      { name: 'Custom Order',      price: 'On consultation',      desc: 'Bring your design · we craft it' },
    ],
  },
  {
    slug:        'electronics-store',
    name:        'Electronics Store',
    emoji:       '📱',
    heroImage:   'https://images.unsplash.com/photo-1498049794561-7780e7231661?w=1200&q=80',
    tagline:     'Product catalog, EMI & service center page',
    description: 'A professional electronics store website with product listings, brand filters, EMI information, and a service/repair booking form — competing with Flipkart on local Google searches.',
    gradient:    'from-blue-600 to-indigo-700',
    lightBg:     'bg-blue-50',
    accentText:  'text-blue-700',
    accentBg:    'bg-blue-600',
    accentHover: 'hover:bg-blue-700',
    price:       '₹9,999', delivery: '7 days', badge: null,
    demoName: 'TechWorld Electronics', demoSub: 'Authorised Dealer · All Brands · Nagpur',
    modalFeatures: [
      { icon: '📱', text: 'Product catalog — mobiles, laptops, TVs, appliances with specs' },
      { icon: '🏷️', text: 'Brand filter — Samsung, Apple, OnePlus, LG, Sony, etc.' },
      { icon: '💳', text: 'EMI information — 0% EMI on HDFC, ICICI cards' },
      { icon: '🔧', text: 'Repair/service booking form — device type, issue, drop-off time' },
      { icon: '📞', text: 'WhatsApp price enquiry on every product' },
      { icon: '🏆', text: 'Authorised dealer certificates for trust' },
    ],
    features: [
      { emoji: '📱', title: 'Product Catalog',  desc: 'Phones, laptops, TVs with specs, price, and WhatsApp enquiry button.' },
      { emoji: '💳', title: 'EMI Information',  desc: '0% EMI available on major cards — displayed clearly on product pages.' },
      { emoji: '🔧', title: 'Service Booking',  desc: 'Repair booking form — device, issue, preferred time, contact.' },
      { emoji: '🏆', title: 'Authorised Dealer', desc: 'Brand certificates build trust and rank above grey-market sellers.' },
    ],
    services: [
      { name: 'Smartphones',    price: '₹8,000–₹1,50,000', desc: 'All brands · exchange available · EMI' },
      { name: 'Laptops',        price: '₹30,000–₹2,00,000', desc: 'Home · gaming · business · EMI' },
      { name: 'Mobile Repair',  price: '₹299+', desc: 'Screen · battery · charging port' },
    ],
  },
  {
    slug:        'grocery-store',
    name:        'Kirana & Grocery',
    emoji:       '🛍️',
    heroImage:   'https://images.unsplash.com/photo-1542838132-92c53300491e?w=1200&q=80',
    tagline:     'Online grocery ordering & home delivery',
    description: 'A simple but powerful grocery website for your kirana store — customers browse and order online, you deliver. No Blinkit commission. Full ownership.',
    gradient:    'from-green-500 to-emerald-600',
    lightBg:     'bg-green-50',
    accentText:  'text-green-700',
    accentBg:    'bg-green-600',
    accentHover: 'hover:bg-green-700',
    price:       '₹9,999', delivery: '7 days', badge: null,
    demoName: 'Fresh Basket Kirana', demoSub: 'Fresh Groceries · Same Day Delivery · Indore',
    modalFeatures: [
      { icon: '🛒', text: 'Online catalog — daily essentials, staples, snacks, beverages' },
      { icon: '📦', text: 'Home delivery request — 2-hr or next-day delivery slot' },
      { icon: '📱', text: 'WhatsApp order option — customers send their list on WhatsApp' },
      { icon: '🔔', text: 'New arrival and sale notifications via WhatsApp broadcast' },
      { icon: '💳', text: 'UPI and Razorpay checkout' },
      { icon: '🗺️', text: 'Delivery area map — show which localities you cover' },
    ],
    features: [
      { emoji: '🛒', title: 'Online Catalog',  desc: 'Categories for staples, dairy, produce, snacks, beverages with prices.' },
      { emoji: '📦', title: 'Home Delivery',   desc: 'Delivery request with address, preferred time slot, and order notes.' },
      { emoji: '📱', title: 'WhatsApp Orders', desc: 'Customers send grocery list on WhatsApp — easiest ordering option.' },
      { emoji: '🗺️', title: 'Delivery Zones', desc: 'Show which localities and societies you deliver to, with minimum order.' },
    ],
    services: [
      { name: 'Staples & Grains',  price: 'MRP',    desc: 'Rice, dal, flour, sugar, oil, spices' },
      { name: 'Fresh Vegetables',  price: 'Daily rate', desc: 'Sourced fresh every morning' },
      { name: 'Home Delivery',     price: '₹30 fee', desc: 'Same-day · orders above ₹300 free' },
    ],
  },
  // ─── AUTO ────────────────────────────────────────────────
  {
    slug:        'car-dealer',
    name:        'Car Dealer',
    emoji:       '🚗',
    heroImage:   'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=1200&q=80',
    tagline:     'Car listings, test drive booking & finance info',
    description: 'A showroom-quality car dealer website with vehicle listings, specifications, photo galleries, EMI calculator, test drive booking, and finance options.',
    gradient:    'from-gray-700 to-slate-800',
    lightBg:     'bg-gray-50',
    accentText:  'text-gray-700',
    accentBg:    'bg-gray-800',
    accentHover: 'hover:bg-gray-900',
    price:       '₹12,999', delivery: '10 days', badge: null,
    demoName: 'AutoPrime Motors', demoSub: 'Authorised New & Pre-owned Cars · Pune',
    modalFeatures: [
      { icon: '🚗', text: 'Vehicle listings — new and used cars with specs and photos' },
      { icon: '📅', text: 'Test drive booking form — model, preferred date, location' },
      { icon: '🧮', text: 'EMI calculator with loan amount and tenure' },
      { icon: '💼', text: 'Finance partners — bank loan, hypothecation info' },
      { icon: '📸', text: 'Full car gallery — exterior, interior, engine' },
      { icon: '🏆', text: 'Authorised dealer certificates' },
    ],
    features: [
      { emoji: '🚗', title: 'Vehicle Listings', desc: 'Each car has specs, colour options, mileage, and photo gallery.' },
      { emoji: '📅', title: 'Test Drive Form',  desc: 'Booking form with model, date, and nearest showroom.' },
      { emoji: '🧮', title: 'EMI Calculator',   desc: 'On-page calculator shows monthly payment for any loan amount.' },
      { emoji: '💼', title: 'Finance Info',     desc: 'Partner bank options, down payment, and approval process explained.' },
    ],
    services: [
      { name: 'Hatchback',    price: '₹5.5L–₹9L',  desc: 'Maruti · Hyundai · Tata' },
      { name: 'Sedan / SUV',  price: '₹10L–₹25L',  desc: 'Honda · Toyota · MG · Kia' },
      { name: 'Pre-owned Car', price: 'From ₹3L',   desc: 'Certified · warranty · RC transfer' },
    ],
  },
  {
    slug:        'bike-showroom',
    name:        'Bike Showroom',
    emoji:       '🏍️',
    heroImage:   'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&q=80',
    tagline:     'Bike listings, test ride & finance options',
    description: 'A powerful bike showroom website with all model listings, specifications, test ride booking, and exchange offers — built to attract serious bike buyers from Google.',
    gradient:    'from-orange-600 to-red-700',
    lightBg:     'bg-orange-50',
    accentText:  'text-orange-600',
    accentBg:    'bg-orange-600',
    accentHover: 'hover:bg-orange-700',
    price:       '₹9,999', delivery: '7 days', badge: null,
    demoName: 'RoadKing Motors', demoSub: 'Authorised Motorcycle Dealer · Jaipur',
    modalFeatures: [
      { icon: '🏍️', text: 'Bike listings — all models with specs, colors, and EMI' },
      { icon: '📅', text: 'Test ride booking form' },
      { icon: '🔄', text: 'Exchange offer calculator' },
      { icon: '🧮', text: 'EMI calculator with loan tenure' },
      { icon: '🏆', text: 'Authorised dealer certifications' },
      { icon: '📱', text: 'WhatsApp enquiry for instant price quote' },
    ],
    features: [
      { emoji: '🏍️', title: 'All Models',       desc: 'Every bike with specs, colour options, mileage, and gallery.' },
      { emoji: '📅', title: 'Test Ride Booking', desc: 'Online test ride request — model, date, time, contact.' },
      { emoji: '🧮', title: 'EMI Calculator',    desc: 'On-page calculator shows monthly payment. Drives purchase decisions.' },
      { emoji: '🔄', title: 'Exchange Offer',    desc: 'Show your exchange/trade-in offer. Reduces purchase barrier.' },
    ],
    services: [
      { name: 'Commuter Bikes', price: '₹65,000–₹1.2L', desc: 'Bajaj · Hero · Honda · TVS' },
      { name: 'Sports Bikes',   price: '₹1.5L–₹5L',     desc: 'Royal Enfield · KTM · Suzuki' },
      { name: 'Service Package', price: '₹1,499/yr',     desc: 'Annual service + oil change + inspection' },
    ],
  },
  {
    slug:        'driving-school',
    name:        'Driving School',
    emoji:       '🚦',
    heroImage:   'https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?w=1200&q=80',
    tagline:     'Course enrollment, schedules & license support',
    description: 'A driving school website where students enroll online, choose their course, book their first lesson, and track their learning progress — modern and easy to navigate.',
    gradient:    'from-blue-500 to-sky-600',
    lightBg:     'bg-sky-50',
    accentText:  'text-sky-700',
    accentBg:    'bg-sky-600',
    accentHover: 'hover:bg-sky-700',
    price:       '₹9,999', delivery: '7 days', badge: null,
    demoName: 'DriveRight School', demoSub: 'Certified Driving Training · Ahmedabad',
    modalFeatures: [
      { icon: '📝', text: 'Online enrollment — 4-wheeler, 2-wheeler, heavy vehicle' },
      { icon: '📅', text: 'Lesson scheduling — pick days and time slots' },
      { icon: '🎓', text: 'RTO license support — test preparation included' },
      { icon: '👨‍🏫', text: 'Certified instructor profiles' },
      { icon: '🚗', text: 'Fleet showcase — training vehicles' },
      { icon: '💳', text: 'Course fee payment with Razorpay' },
    ],
    features: [
      { emoji: '📝', title: 'Online Enrollment', desc: 'Students pick course, schedule, and pay online. No office visit needed.' },
      { emoji: '📅', title: 'Flexible Scheduling', desc: 'Morning, afternoon, evening slots. Student picks what works for them.' },
      { emoji: '🎓', title: 'License Support',  desc: 'RTO test preparation, document checklist, and appointment guidance.' },
      { emoji: '👨‍🏫', title: 'Instructor Profiles', desc: 'Certified instructors with experience and student ratings.' },
    ],
    services: [
      { name: '4-Wheeler Course',  price: '₹3,500', desc: '28 days · 1 hr/day · RTO support included' },
      { name: '2-Wheeler Course',  price: '₹1,500', desc: '14 days · 45 min/day' },
      { name: 'Refresher Course',  price: '₹1,000', desc: '7 sessions · for licensed drivers' },
    ],
  },
  // ─── HOME SERVICES ───────────────────────────────────────
  {
    slug:        'packers-movers',
    name:        'Packers & Movers',
    emoji:       '📦',
    heroImage:   'https://images.unsplash.com/photo-1600880292203-757bb62b4baf?w=1200&q=80',
    tagline:     'Moving quotes, services & trust building',
    description: 'A trustworthy packers & movers website with instant quote forms, service types, customer reviews, and insurance information — converting anxious movers into confirmed bookings.',
    gradient:    'from-amber-600 to-orange-600',
    lightBg:     'bg-amber-50',
    accentText:  'text-amber-700',
    accentBg:    'bg-amber-600',
    accentHover: 'hover:bg-amber-700',
    price:       '₹9,999', delivery: '7 days', badge: null,
    demoName: 'SafeMove Packers', demoSub: 'Trusted Relocation Services · Pan India',
    modalFeatures: [
      { icon: '📋', text: 'Instant quote form — from city, to city, move type, date' },
      { icon: '📦', text: 'Services — local shifting, intercity, office relocation, vehicle transport' },
      { icon: '🛡️', text: 'Insurance & damage protection info prominently shown' },
      { icon: '⭐', text: 'Verified customer reviews and star ratings' },
      { icon: '📱', text: 'WhatsApp quote request option' },
      { icon: '📅', text: 'Booking calendar with available dates' },
    ],
    features: [
      { emoji: '📋', title: 'Quick Quote Form', desc: 'From city → to city, move type, date. You get a lead, they get a quote in 15 min.' },
      { emoji: '🛡️', title: 'Insurance Info',  desc: 'Showing damage protection builds immediate trust over competitors.' },
      { emoji: '⭐', title: 'Real Reviews',     desc: 'Google review integration. Moving is stressful — reviews close the deal.' },
      { emoji: '📱', title: 'WhatsApp Quote',   desc: 'Quick WhatsApp button for urgent queries. High conversion rate.' },
    ],
    services: [
      { name: 'Local Shifting (1BHK)', price: '₹3,500+', desc: 'Same city · packing + loading + unloading' },
      { name: 'Intercity Move (2BHK)', price: '₹12,000+', desc: 'Pan India · packed + insured' },
      { name: 'Vehicle Transport',     price: '₹8,000+',  desc: 'Car · bike · on carrier truck' },
    ],
  },
  // ─── SOCIAL / MISC ──────────────────────────────────────
  {
    slug:        'ngo',
    name:        'NGO & Trust',
    emoji:       '🤝',
    heroImage:   'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=1200&q=80',
    tagline:     'Donations, impact stories & transparency',
    description: 'A transparent and inspiring NGO website that tells your impact story, shows where donations go, enables online donations with Razorpay, and builds long-term donor trust.',
    gradient:    'from-emerald-600 to-green-700',
    lightBg:     'bg-emerald-50',
    accentText:  'text-emerald-700',
    accentBg:    'bg-emerald-600',
    accentHover: 'hover:bg-emerald-700',
    price:       '₹9,999', delivery: '7 days', badge: null,
    demoName: 'HopeRise Foundation', demoSub: 'Education · Healthcare · Women Empowerment',
    modalFeatures: [
      { icon: '❤️', text: 'Online donation with Razorpay — UPI, cards, 80G tax receipt' },
      { icon: '📊', text: 'Impact counter — lives touched, projects completed, funds raised' },
      { icon: '📸', text: 'Stories and photo gallery from field work' },
      { icon: '📋', text: 'Projects page — ongoing and completed initiatives' },
      { icon: '🤝', text: 'Volunteer registration form' },
      { icon: '🏛️', text: 'Registration certificates — 80G, 12A, FCRA for donor trust' },
    ],
    features: [
      { emoji: '❤️', title: 'Online Donations', desc: 'Razorpay donation with amount presets. 80G receipt auto-generated.' },
      { emoji: '📊', title: 'Impact Counters',  desc: 'Live numbers — lives touched, villages covered, meals served.' },
      { emoji: '🏛️', title: 'Transparency',    desc: '80G, 12A, FCRA certificates shown prominently. Builds trust.' },
      { emoji: '📸', title: 'Impact Stories',   desc: 'Beneficiary stories and photos connect emotionally with donors.' },
    ],
    services: [
      { name: 'Education Program',    price: '₹500/month sponsors a child', desc: 'School fees · books · uniform' },
      { name: 'Healthcare Initiative', price: '₹1,000 funds a camp',        desc: 'Medical checkup for 10 families' },
      { name: 'Volunteer Program',    price: 'Free',                          desc: 'Register and contribute your skills' },
    ],
  },
  // ─── TRANSPORT ────────────────────────────────────────
  {
    slug:        'goods-transport',
    name:        'Goods Transport',
    emoji:       '🚛',
    heroImage:   'https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?w=1200&q=80',
    tagline:     'Fleet management, bookings & route tracking',
    description: 'A professional goods transport website where shippers book vehicles online, track consignments, and get instant freight quotes — cutting out middlemen.',
    gradient:    'from-orange-600 to-amber-700',
    lightBg:     'bg-orange-50',
    accentText:  'text-orange-700',
    accentBg:    'bg-orange-600',
    accentHover: 'hover:bg-orange-700',
    price:       '₹12,999', delivery: '10 days', badge: null,
    demoName: 'FastMove Logistics', demoSub: 'Pan India Goods Transport · Trusted Since 2008',
    modalFeatures: [
      { icon: '📦', text: 'Online booking — pickup city, drop city, weight, vehicle type' },
      { icon: '🚛', text: 'Fleet showcase — mini truck, full truck, trailer, container' },
      { icon: '💰', text: 'Instant freight quote calculator' },
      { icon: '📍', text: 'Consignment tracking with live status updates' },
      { icon: '📱', text: 'WhatsApp updates — dispatch, in-transit, delivered' },
      { icon: '📋', text: 'LR (Lorry Receipt) generation for each shipment' },
    ],
    features: [
      { emoji: '📦', title: 'Online Booking',   desc: 'Shippers book pickup online — origin, destination, weight, vehicle needed.' },
      { emoji: '🚛', title: 'Fleet Showcase',   desc: 'Show available vehicle types with capacity, rates, and availability.' },
      { emoji: '📍', title: 'Live Tracking',    desc: 'Consignment status visible to the shipper — dispatched, in-transit, delivered.' },
      { emoji: '💰', title: 'Freight Quote',    desc: 'Instant per-km or zone-based quote calculator drives more enquiries.' },
    ],
    services: [
      { name: 'Mini Truck (up to 1 ton)',   price: '₹18/km', desc: 'Local & intercity · same-day dispatch' },
      { name: 'Full Truck (up to 10 ton)',  price: '₹14/km', desc: 'Pan India · dedicated vehicle' },
      { name: 'Part Load / LCL',            price: 'On quote', desc: 'Share truck space · cost-effective' },
    ],
  },
]
